import Footer from '@components/Footer';
import Navbar from '@components/Navbar';
import Providers from './Providers';
import './globals.css';
import { Aclonica, Oswald } from 'next/font/google';

const aclonica = Aclonica({
  subsets: ['latin'],
  weight: ['400']
});

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400']
});

export const metadata = {
  title: 'Nefrochat',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen flex flex-col'>
        <Providers>
          <nav>
            <Navbar />
          </nav>
          <main className={"flex-1 " + oswald.className}>{children}</main>
          <div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
